import { useEffect, useState } from "react";
import { getHealthProfile, updateHealthProfile } from "../api.js";

const emptyTargets = { beforeMin: 70, beforeMax: 140, afterMin: 70, afterMax: 180 };

export default function CarePlanPage() {
  const [form, setForm] = useState({ conditions: "", medications: "", glucoseTargets: emptyTargets, exerciseLimits: "", lowGlucoseInstructions: "", sickDayInstructions: "", clinicianNotes: "" });
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { getHealthProfile().then((data) => setForm({ ...data, conditions: (data.conditions || []).join("\n"), medications: (data.medications || []).map((item) => [item.name, item.dose, item.timing, item.instructions].join(" | ")).join("\n"), glucoseTargets: data.glucoseTargets || emptyTargets })).catch((err) => setMessage(err.message)); }, []);
  function patch(key, value) { setForm((current) => ({ ...current, [key]: value })); }
  function target(key, value) { setForm((current) => ({ ...current, glucoseTargets: { ...current.glucoseTargets, [key]: value } })); }
  async function save(event) { event.preventDefault(); setSaving(true); setMessage(""); try { const data = await updateHealthProfile({ ...form, conditions: form.conditions.split("\n").map((item) => item.trim()).filter(Boolean), medications: form.medications.split("\n").map((line) => { const [name, dose, timing, instructions] = line.split("|").map((item) => item?.trim() || ""); return { name, dose, timing, instructions }; }).filter((item) => item.name), glucoseTargets: Object.fromEntries(Object.entries(form.glucoseTargets).map(([key, value]) => [key, Number(value)])) }); setForm((current) => ({ ...current, glucoseTargets: data.glucoseTargets })); setMessage("Care plan saved."); } catch (err) { setMessage(err.message); } finally { setSaving(false); } }
  const textClass = "w-full rounded-xl border border-line bg-surface px-3 py-2.5 text-sm outline-none focus:border-cyan/50";
  return <div className="page-pad"><p className="text-[12px] tracking-[0.18em] text-coral uppercase">My Health · My care plan</p><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">My care plan</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Keep the instructions agreed with your clinician in one place. This page stores your plan; it does not calculate treatment changes.</p><form onSubmit={save} className="mt-7 max-w-4xl space-y-5"><Panel title="Conditions"><textarea rows={3} value={form.conditions} onChange={(e) => patch("conditions", e.target.value)} placeholder="One condition per line" className={textClass}/></Panel><Panel title="Medicines"><textarea rows={4} value={form.medications} onChange={(e) => patch("medications", e.target.value)} placeholder="One per line: Name | Dose | Timing | Instructions" className={textClass}/><p className="mt-2 text-xs text-muted">Example: Insulin name | prescribed dose | before breakfast | clinician instructions</p></Panel><Panel title="Clinician-set glucose targets"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["beforeMin","Before food min"],["beforeMax","Before food max"],["afterMin","After food min"],["afterMax","After food max"]].map(([key,label]) => <label key={key}><span className="mb-1.5 block text-xs text-muted">{label}</span><input type="number" min="20" max="800" value={form.glucoseTargets?.[key] ?? ""} onChange={(e) => target(key, e.target.value)} className={textClass}/></label>)}</div><p className="mt-2 text-xs text-muted">These values control “below target,” “in target,” and “above target” labels on the Sugar page. The initial values are placeholders—confirm and replace them with the targets given by your clinician.</p></Panel><Panel title="Exercise limits and instructions"><textarea rows={3} value={form.exerciseLimits} onChange={(e) => patch("exerciseLimits", e.target.value)} className={textClass}/></Panel><Panel title="Low-glucose instructions"><textarea rows={4} value={form.lowGlucoseInstructions} onChange={(e) => patch("lowGlucoseInstructions", e.target.value)} placeholder="Write the exact steps agreed with your diabetes team." className={textClass}/></Panel><Panel title="Sick-day and ketone instructions"><textarea rows={4} value={form.sickDayInstructions} onChange={(e) => patch("sickDayInstructions", e.target.value)} placeholder="Write the exact sick-day plan agreed with your diabetes team." className={textClass}/></Panel><Panel title="Other clinician notes"><textarea rows={4} value={form.clinicianNotes} onChange={(e) => patch("clinicianNotes", e.target.value)} className={textClass}/></Panel>{message ? <p className={`text-sm ${message.includes("saved") ? "text-teal" : "text-coral"}`}>{message}</p> : null}<button type="submit" disabled={saving} className="rounded-xl bg-cyan px-5 py-2.5 text-sm font-semibold text-[#102024] disabled:opacity-50">{saving ? "Saving…" : "Save care plan"}</button></form></div>;
}
function Panel({ title, children }) { return <section className="rounded-2xl border border-line bg-raised/80 p-4 sm:p-5"><h2 className="mb-3 text-sm font-semibold">{title}</h2>{children}</section>; }
