import { useEffect, useMemo, useState } from "react";
import { getExerciseSessions, getInsulinEntries, getMealLogs, getSleepLogs, getSugarReadings } from "../api.js";

const PERIODS = [{ id:7,label:"7 days"},{id:30,label:"30 days"},{id:90,label:"90 days"}];
function pad(n){return String(n).padStart(2,"0")}
function keyOf(value){const d=new Date(value);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function days(count){const result=[];const now=new Date();now.setHours(0,0,0,0);for(let i=0;i<count;i+=1){const d=new Date(now);d.setDate(d.getDate()-i);result.push(keyOf(d))}return result}
function avg(values){return values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):null}
function formatDay(key){return new Date(`${key}T12:00:00`).toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})}

export default function HealthTrendsPage(){
  const[period,setPeriod]=useState(30);const[data,setData]=useState({sugar:[],insulin:[],meals:[],sleep:[],exercise:[]});const[error,setError]=useState("");
  useEffect(()=>{Promise.all([getSugarReadings("real"),getInsulinEntries(),getMealLogs(),getSleepLogs(),getExerciseSessions()]).then(([sugar,insulin,meals,sleep,exercise])=>setData({sugar:sugar.readings||[],insulin:insulin.entries||[],meals:meals.logs||[],sleep:sleep.logs||[],exercise:exercise.sessions||[]})).catch(err=>setError(err.message))},[]);
  const rows=useMemo(()=>days(period).map(day=>{const sugar=data.sugar.filter(item=>keyOf(item.recordedAt)===day);const insulin=data.insulin.filter(item=>keyOf(item.recordedAt)===day);const meals=data.meals.filter(item=>item.day===day);const sleep=data.sleep.find(item=>item.day===day);const exercise=data.exercise.filter(item=>keyOf(item.recordedAt)===day);return{day,sugarAvg:avg(sugar.map(item=>item.level)),sugarCount:sugar.length,above:sugar.filter(item=>item.status==="above target").length,insulin:insulin.reduce((sum,item)=>sum+Number(item.dose||0),0),eaten:meals.filter(item=>item.status==="eaten").length,skipped:meals.filter(item=>item.status==="skipped").length,loggedMeals:meals.length,sleep:sleep?.actualSleepMinutes??sleep?.durationMinutes??null,activity:exercise.reduce((sum,item)=>sum+Number(item.durationMinutes||0),0)}}),[data,period]);
  const recorded=rows.filter(row=>row.sugarCount||row.insulin||row.loggedMeals||row.sleep||row.activity);
  return <div className="page-pad"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[12px] tracking-[0.18em] text-coral uppercase">My Health · Trends</p><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">Health trends</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Compare glucose, insulin, meals, sleep, and exercise by date. Shared timing can suggest questions to discuss; it does not prove that one event caused another.</p></div><div className="flex rounded-xl bg-white/4 p-1">{PERIODS.map(item=><button key={item.id} onClick={()=>setPeriod(item.id)} className={`rounded-lg px-3 py-1.5 text-xs ${period===item.id?"bg-white/10 text-ink":"text-muted"}`}>{item.label}</button>)}</div></div>{error?<p className="mt-4 text-sm text-coral">{error}</p>:null}<div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Days with data" value={recorded.length}/><Stat label="Glucose readings" value={rows.reduce((s,r)=>s+r.sugarCount,0)}/><Stat label="Insulin recorded" value={`${Math.round(rows.reduce((s,r)=>s+r.insulin,0)*10)/10} u`}/><Stat label="Meals logged" value={rows.reduce((s,r)=>s+r.loggedMeals,0)}/><Stat label="Movement" value={`${rows.reduce((s,r)=>s+r.activity,0)} min`}/></div><div className="mt-6 overflow-hidden rounded-2xl border border-line bg-raised/80"><div className="grid grid-cols-[8rem_repeat(5,minmax(7rem,1fr))] gap-2 border-b border-line bg-white/4 px-4 py-3 text-[11px] font-medium uppercase tracking-wide text-muted"><span>Date</span><span>Glucose</span><span>Insulin</span><span>Meals</span><span>Sleep</span><span>Movement</span></div><div data-lenis-prevent className="max-h-[38rem] overflow-auto overscroll-contain">{rows.map(row=><div key={row.day} className="grid min-w-[52rem] grid-cols-[8rem_repeat(5,minmax(7rem,1fr))] gap-2 border-b border-line/45 px-4 py-3 text-xs last:border-0"><span className="font-medium text-ink">{formatDay(row.day)}</span><Cell value={row.sugarAvg!=null?`${row.sugarAvg} mg/dL`:"—"} sub={row.sugarCount?`${row.sugarCount} reading${row.sugarCount===1?"":"s"}${row.above?` · ${row.above} above target`:""}`:"not logged"}/><Cell value={row.insulin?`${row.insulin} u`:"—"} sub={row.insulin?"recorded total":"not logged"}/><Cell value={row.loggedMeals?`${row.eaten} eaten · ${row.skipped} skipped`:"—"} sub={`${4-row.loggedMeals} not logged`}/><Cell value={row.sleep?`${Math.floor(row.sleep/60)}h ${row.sleep%60}m`:"—"} sub={row.sleep?"recorded":"not logged"}/><Cell value={row.activity?`${row.activity} min`:"—"} sub={row.activity?"recorded":"not logged"}/></div>)}</div></div><p className="mt-4 text-xs leading-5 text-muted">“Not logged” means the app has no record for that item; it does not mean the meal, medicine, sleep, or activity did not happen.</p></div>;
}
function Stat({label,value}){return <div className="rounded-2xl border border-line bg-raised/80 p-4"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>}
function Cell({value,sub}){return <span><span className="block text-ink">{value}</span><span className="mt-1 block text-[10px] text-muted">{sub}</span></span>}
